camera_extrinsics:
  pitch: 0.48
  roll: 0.0
  x: 0.17
  y: 0.02
  yaw: 0.0
  z: 0.25
ekf:
  frequency: 50
  sensor_timeout: 0.2
face_point:
  align_deg: 90.0
  ang_floor: 0.3
  ang_kp: 2.5
  ang_max: 0.45
  distance_m: 0.45
  reverse_speed: 2.0
  timeout_sec: 10.0
  yaw_tol_deg: 8.0
imu:
  gyro_bias_x: -0.008988
  gyro_bias_y: -0.004757
  gyro_bias_z: 0.003812
kinect:
  backlight_compensation: false
  brightness: 128
  color_resolution: 720P
  contrast: 5
  depth_mode: NFOV_2X2BINNED
  exposure_time_absolute: 5000
  fps: 15
  gain: 255
  powerline_frequency: 60
  saturation: 32
  sharpness: 2
  white_balance: 4500
