camera_extrinsics:
  pitch: 0.48
  roll: 0.0
  x: 0.17
  y: 0.0
  yaw: 0.0
  z: 0.25
ekf:
  frequency: 50
  sensor_timeout: 0.2
imu:
  gyro_bias_x: -0.00855
  gyro_bias_y: -0.002707
  gyro_bias_z: 0.00426
kinect:
  backlight_compensation: false
  brightness: 128
  color_resolution: 720P
  contrast: 5
  depth_mode: NFOV_UNBINNED
  exposure_time_absolute: -1
  fps: 15
  gain: -1
  powerline_frequency: 60
  saturation: 32
  sharpness: 2
  white_balance: -1
