name: igvi_robot

x-base-service: &base_service
  env_file:
    - ../.env
  networks:
    - robot_net

x-config-volume: &config_volume ../../../robot_ws/configs:/configs:ro
x-launch-volume: &launch_volume ../../../robot_ws/launch:/workspace/launch:ro
x-igvi-imu-volume: &igvi_imu_volume ../../../robot_ws/src/igvi_imu/igvi_imu:/workspaces/src/igvi_imu/igvi_imu:ro

services:
  camera_kinect:
    <<: *base_service
    profiles: ["sensors", "kinect"]
    build:
      context: ../../..
      dockerfile: docker/images/Dockerfile.kinect
    image: wildbot_kinect:latest
    restart: unless-stopped
    environment:
      FASTRTPS_DEFAULT_PROFILES_FILE: /configs/fastdds_shm.xml
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - *config_volume
      - *launch_volume
      - *igvi_imu_volume
      - /dev/shm:/dev/shm
    command:
      - /bin/bash
      - -c
      - >-
        ros2 run azure_kinect_ros_driver node --ros-args
        -p depth_enabled:=true
        -p color_enabled:=true
        -p color_resolution:=720P
        -p depth_mode:=NFOV_UNBINNED
        -p fps:=15
        -p imu_rate_target:=200
        -p point_cloud:=true
        -p rgb_point_cloud:=true
        -p color_white_balance:=4500 
        -p color_exposure_time:=15625 
        -p color_gain:=128 
        -p color_brightness:=128 
        -p color_contrast:=5 
        -p color_saturation:=32 
        -p color_sharpness:=2 
        -p color_backlight_compensation:=0 
        -p color_powerline_frequency:=2

networks:
  robot_net:
    driver: bridge
