name: igvi_robot

x-base-service: &base_service
  env_file:
    - ../.env
  networks:
    - robot_net

x-config-volume: &config_volume ../../../robot_ws/configs:/configs:ro
x-launch-volume: &launch_volume ../../../robot_ws/launch:/workspace/launch:ro
x-igvi-imu-volume: &igvi_imu_volume ../../../robot_ws/src/igvi_imu/igvi_imu:/workspaces/src/igvi_imu/igvi_imu:ro

services:
  camera_kinect:
    <<: *base_service
    profiles: ["sensors", "kinect"]
    build:
      context: ../../..
      dockerfile: docker/images/Dockerfile.kinect
    image: wildbot_kinect:latest
    environment:
      FASTRTPS_DEFAULT_PROFILES_FILE: /configs/fastdds_shm.xml
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - *config_volume
      - *launch_volume
      - *igvi_imu_volume
      - /dev/shm:/dev/shm
    command:
      - /bin/bash
      - -c
      - >-
        source /workspaces/install/setup.bash &&
        ros2 launch /workspace/launch/kinect_bringup.launch.py

networks:
  robot_net:
    driver: bridge
