name: igvi_robot

x-base-service: &base_service
  env_file:
    - ../.env
  networks:
    - robot_net

services:
  foxglove_bridge:
    <<: *base_service
    profiles: ["monitoring"]
    build:
      context: ../../..
      dockerfile: docker/images/Dockerfile.foxglove
    image: wildbot_foxglove_bridge:latest
    ports:
      - 8765:8765
    command: >
      ros2 launch foxglove_bridge foxglove_bridge_launch.xml
      port:=8765
      max_qos_depth:=1
      send_buffer_limit:=10000000

networks:
  robot_net:
    driver: bridge
