name: igvi_robot

x-base-service: &base_service
  env_file:
    - ../.env
  networks:
    - robot_net

services:
  lidar_filter:
    <<: *base_service
    profiles: ["sensors", "lidar"]
    image: ghcr.io/screamlab/wildbot_base_image:latest
    command: ros2 run lidar_pkg lidar_nan_value_filter_node

networks:
  robot_net:
    driver: bridge
