name: igvi_robot

x-base-service: &base_service
  env_file:
    - ../.env
  networks:
    - robot_net

x-config-volume: &config_volume ../../../robot_ws/configs:/configs:ro

services:
  motion_arbiter:
    <<: *base_service
    profiles: ["robot"]
    build:
      context: ../../..
      dockerfile: docker/images/Dockerfile.motion
    environment:
      FASTRTPS_DEFAULT_PROFILES_FILE: /configs/fastdds_shm.xml
    volumes:
      - *config_volume
      - ../../../robot_ws/src/motion_arbiter/motion_arbiter:/workspace/src/motion_arbiter/motion_arbiter:ro
    restart: unless-stopped

networks:
  robot_net:
    driver: bridge
